Лабораторная работа 1   
Метод Гаусса с выбором главного значения по матрице  
$$
A = 
\begin{bmatrix}
 0,4974 &  0,0000 & -0,1299 &  0,0914 &  0,1523 \\
-0,0305 &  0,3248 &  0,0000 & -0,0619 &  0,0203 \\
 0,0102 & -0,0914 &  0,5887 &  0,0112 &  0,0355 \\
 0,0305 &  0,0000 & -0,0741 &  0,5887 &  0,0000 \\
 0,0203 & -0,0305 &  0,1472 & -0,0122 &  0,4263
\end{bmatrix}
\quad \quad
b = 
\begin{bmatrix}
 1,5875 \\
-1,7590 \\
 1,4139 \\
 1,7702 \\
-2,0767
\end{bmatrix}
$$



In [4]:
import numpy as np

In [ ]:
A = np.array([
    [ 0.4974,  0.0000, -0.1299,  0.0914,  0.1523],
    [-0.0305,  0.3248,  0.0000, -0.0619,  0.0203],
    [ 0.0102, -0.0914,  0.5887,  0.0112,  0.0355],
    [ 0.0305,  0.0000, -0.0741,  0.5887,  0.0000],
    [ 0.0203, -0.0305,  0.1472, -0.0122,  0.4263]
])
B = np.array([
    [ 1.5875],
    [-1.7590],
    [ 1.4139],
    [ 1.7702],
    [-2.0767]
])



5


In [ ]:
def find_swap_not_zero(A, k):
    for i in range(k + 1, A.shape[0]):
        if A[i][k] != 0:
            A[[k, i]] = A[[i, k]]
            return

def find_swap_leading_element(A, k, p):
    max_ = abs(A[k][k])
    ind_i, ind_j = k, k
    for i in range(k, A.shape[0]):
        for j in range(k, A.shape[0]):
            if abs(A[i][j]) > max_:
                ind_i, ind_j = i, j
                max_ = abs(A[i][j])
    if ind_i != k:
        A[[k, ind_i]] = A[[ind_i, k]]
    if ind_j != k:
        A[:, [k, ind_j]] = A[:, [ind_j, k]]
    p[k], p[ind_j] = p[ind_j], p[k]


def Gauss_right(a, b):
    n = b.shape[0]
    m = a.shape[1] + b.shape[1]
    p = np.arange(n)
    A = np.hstack((a, b))
    for k in range(n - 1):
        find_swap_leading_element(A, k, p)
        for i in range(k + 1, n):
            b = A[i][k] / A[k][k]
            for j in range(k + 1, m):
                A[i][j] = A[i][j] - A[k][j] * b
    return A, p

def Gauss_inv(A, p):
    n, m = A.shape
    x = np.zeros(n) 
    x[n - 1] = A[n - 1][m - 1]/A[n - 1][m - 2]
    for k in range(n - 2, -1, -1):
        sum = 0
        for j in range(k + 1, m - 1):
            sum += A[k][j] * x[j]
        x[k] = A[k][m - 1] - sum  
    x_correct = np.zeros(n)
    for i in range(n):
        x_correct[p[i]] = x[i]
    return x

In [54]:
a = np.array([[ 1.0,  1.0,  1.0], 
              [ 2.0,  3.0,  1.0], 
              [ 1.0, -1.0,  2.0]])

b = np.array([[ 6.0], 
              [11.0], 
              [ 5.0]])
print(Gauss_right(a,b))
print(Gauss_inv(Gauss_right(a,b)))

[[ 1.  1.  1.  6.]
 [ 2.  1. -1. -1.]
 [ 1. -2. -1. -3.]]
[1. 2. 3.]
